### ISSUE TITLE
Support version 0.9.0

### ISSUE THREAD

**Issue by eborden** [frontrowed/faktory_worker_haskell#28]
`faktory_worker_haskell` is built for version 0.8.0. We need to make sure it works with 0.9.0.

**Comment by eborden** [comment]
https://github.com/contribsys/faktory/blob/master/Changes.md#090

- Now uses Redis https://github.com/contribsys/faktory/pull/160
  Shouldn't influence the interface.
- Supports middleware https://github.com/contribsys/faktory/pull/168
  Probably not something we need to worry about.
- Supports TOML configs https://github.com/contribsys/faktory/pull/169
  Also doesn't seem to influence the protocol

**Comment by pbrisbin** [comment]
Closed via #31 -- we run CI on 0.9.0 now.
